name: Update README Date

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README dates
        run: |
          # Create the template content with 'somedate'
          cat > README.md << 'EOL'
# uhhhhh...

\`future goals: webhooks, key verifying\`



***Fill out somedate with the format after:YEAR-MONTH-DAY or after:YEAR***

old keys
\`\`\`
"sk-" "openai" after:somedate
"sk-" "openai" "gpt-3.5" after:somedate
"sk-" "openai" "gpt-4" after:somedate
"sk-" "openai" "gpt-4o" after:somedate
"sk-" "openai" "gpt-o1" after:somedate
\`\`\`

new keys
\`\`\`
"sk-proj-" after:somedate
"sk-proj-" "gpt-3.5" after:somedate
"sk-proj-" "gpt-4" after:somedate
"sk-proj-" "gpt-4o" after:somedate
"sk-proj-" "gpt-o1" after:somedate
\`\`\`
EOL

          # Get current date minus 2 days in required format
          date=$(date -d "2 days ago" '+%Y-%m-%d')
          
          # Replace all instances of 'somedate' with the calculated date
          perl -i -pe "s/somedate/$date/g" README.md
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update dates to ${date}" && git push)
